name = "VertexModels"                                                                                  
uuid = "a9701cb2-eaf6-4df2-88fa-f3d2a2d195a7"                                                                      
version = "0.1.0" 
